### ISSUE TITLE
Diagramas de caso de uso

### ISSUE THREAD

**Issue by seziniestudante** [Victornnunes/GrewBills#6]
- [x] @Victornnunes Criar diagrama de casos de uso: 
 Modelar diagrama de casos de uso utilizando notação UML. O aluno deverá salvar os arquivos originais do projeto UML dentro da pasta requisitos. O documento de requisitos deverá ser atualizado e os diagramas de casos de uso devem ser inseridos nele, na seção específica para isto.

- [x] @Victornnunes  Documentar cenários de caso de uso
Fazer a descrição detalhada de 8 casos de uso, sendo 4 requisitos referente as operações CRUD com uma tabela e mais 4 requisitos referente as operações CRUD com três ou mais tabelas. A funcionalidade de Login será obrigatória para qualquer funcionalidade do sistema e deverá estar devidamente documentado/representado. A descrição detalhada dos casos de uso deverá seguir o modelo de campos descritos na última página do Trabalho e Casos de Uso disponível na sala virtual. A entrega deverá ser pelo próprio repositório do projeto onde o aluno deverá atualizar o documento de requisitos inserindo a descrição após cada diagrama feito. Poderá haver um único diagrama ou poderá haver diagramas separados pela visão do usuário.

**Comment by Victornnunes** [comment]
Diagrama de casos de uso pronto
